export default [{
    "MachineNo": "699638289-0",
    "PropertyNo": "699638289-0",
    "Value": "32 CFU/ml",
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": "2018-11-01T07:23:42+00:00",
    "ResolvedTime": "2018-11-01T07:23:42+00:00",
    "CreatedTime": "2018-11-01T07:23:42+00:00",
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": 'admin',
    "Source": "manual",
    "IsResolved": true,
    "CreatedUserName": 'admin',
    "ResolvedUserName": 'admin',
    "ResolvedUserId": '1234',
    "ResolvedWay": "replace the ro Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}, {
    "MachineNo": 38,
    "PropertyNo": "230524730-3",
    "Value": 55,
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "Source": "his",
    "ModifiedUserName": null,
    "CreatedUserName": 'admin',
    "IsResolved": true,
    "ResolvedUserName": '但陳鄭愷'
}, {
    "MachineNo": 10,
    "PropertyNo": "603005494-5",
    "Value": 58,
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": null,
    "AbnormalReason": null,
    "ModifiedUserName": null,
    "IsResolved": true,
    "ResolvedUserName": '但陳鄭愷'
}, {
    "MachineNo": 43,
    "PropertyNo": "303563776-8",
    "Value": 3,
    "AbnormalTime": "2018-10-01T07:23:17+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": "Admin"
}, {
    "MachineNo": 88,
    "PropertyNo": "676807681-7",
    "Value": 93,
    "AbnormalTime": "2018-10-01T07:23:17+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": "Admin"
}, {
    "MachineNo": 77,
    "PropertyNo": "204505024-6",
    "Value": 27,
    "AbnormalTime": "2018-10-01T07:23:17+00:00",
    "ModifiedTime": "2018-10-01T07:23:17+00:00",
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": "Admin"
}, {
    "MachineNo": 58,
    "PropertyNo": "235155189-3",
    "Value": 12,
    "AbnormalTime": "2018-10-01T07:23:17+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": "Admin"
}, {
    "MachineNo": "699638289-0",
    "PropertyNo": "699638289-0",
    "Value": 32,
    "Unit": "CFU/ml",
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": null,
    "Source": "manual",
    "CreatedUserName": 'admin',
    "ResolvedUserName": 'admin',
    "ResolvedUserId": '1234',
    "ResolvedWay": "replace the ro Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}, {
    "MachineNo": 40,
    "PropertyNo": "562533392-0",
    "Value": 69,
    "AbnormalTime": "2018-10-01T07:23:17+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": "Admin"
}, {
    "MachineNo": 78,
    "PropertyNo": "697331555-0",
    "Value": 64,
    "AbnormalTime": "2018-10-01T07:23:17+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "",
    "ModifiedUserName": "Admin"
}, {
    "MachineNo": "699638289-0",
    "PropertyNo": "699638289-0",
    "Value": 32,
    "Unit": "CFU/ml",
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": null,
    "Source": "manual",
    "CreatedUserName": 'admin',
    "ResolvedUserName": 'admin',
    "ResolvedUserId": '1234',
    "ResolvedWay": "replace the ro Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}, {
    "MachineNo": "699638289-0",
    "PropertyNo": "699638289-0",
    "Value": 32,
    "Unit": "CFU/ml",
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": null,
    "Source": "manual",
    "CreatedUserName": 'admin',
    "ResolvedUserName": 'admin',
    "ResolvedUserId": '1234',
    "ResolvedWay": "replace the ro Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}, {
    "MachineNo": "699638289-0",
    "PropertyNo": "699638289-0",
    "Value": 32,
    "Unit": "CFU/ml",
    "AbnormalTime": "2018-11-01T07:23:42+00:00",
    "ModifiedTime": null,
    "AbnormalReason": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    "ModifiedUserName": null,
    "Source": "manual",
    "CreatedUserName": 'admin',
    "ResolvedUserName": 'admin',
    "ResolvedUserId": '1234',
    "ResolvedWay": "replace the ro Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}]